"""
Configuration Module
Contains all settings, theme definitions, and internationalization (I18N) texts.
"""
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# OpenRouter API (OpenAI-compatible)
OPENROUTER_BASE_URL = os.getenv(
    "OPENROUTER_BASE_URL",
    "https://openrouter.ai/api/v1",
)
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "openai/gpt-4o")
CLAUDE_MAX_TOKENS = 8192

# RSS Feed Configuration
RSS_URL = os.getenv("RSS_URL", "https://news.smol.ai/rss.xml")
RSS_TIMEOUT = 30     

# Output and Deployment Configuration
OUTPUT_DIR = os.getenv("OUTPUT_DIR", "docs")
GITHUB_PAGES_URL = os.getenv("GITHUB_PAGES_URL", "")

def _get_env_int(key: str, default: int) -> int:
    """Helper to get integer environment variables with a default value"""
    value = os.getenv(key)
    if value is None or value == "":
        return default
    return int(value)

# Email Notification Configuration (SMTP)
SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = _get_env_int("SMTP_PORT", 587)
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
NOTIFICATION_TO = os.getenv("NOTIFICATION_TO")

# Theme Definitions for the generated HTML
THEMES = {
    "blue": {
        "name": "Tech Blue",
        "description": "Minimalist tech style, suitable for AI news",
        "glow_start": "#1e3a8a",
        "glow_end": "#1e40af",
        "title": "#1e293b",
        "text": "#475569",
        "accent": "#3b82f6",
        "secondary": "#64748b",
        "gradient": "linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)"
    }
}

# Internationalization (I18N) Texts
I18N = {
    "zh": {
        "title": "Tomato AI Daily",
        "subtitle": "AI News Daily",
        "highlights": "Today's Highlights",
        "keywords": "Keywords",
        "read_more": "Read More",
        "empty_title": "No News Today",
        "back_to_home": "Back to Home",
        "footer_text": "Generated by Tomato AI",
        "date_format": "%Y-%m-%d",
        "weekdays": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        "categories": {
            "model": "Models",
            "product": "Products",
            "research": "Research",
            "tools": "Tools",
            "funding": "Funding",
            "events": "Events"
        }
    },
    "en": {
        "title": "Tomato AI Daily",
        "subtitle": "AI Tech News Daily",
        "highlights": "Highlights",
        "keywords": "Keywords",
        "read_more": "Read More",
        "empty_title": "No News Today",
        "back_to_home": "Back to Home",
        "footer_text": "Generated by Tomato AI",
        "date_format": "%B %d, %Y",
        "weekdays": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "categories": {
            "model": "Models",
            "product": "Products",
            "research": "Research",
            "tools": "Tools",
            "funding": "Funding",
            "events": "Events"
        }
    }
}

# News Categories and their descriptions
CATEGORIES = {
    "model": {
        "name": "Models",
        "icon": "🤖",
        "description": "New models / Version updates / Architecture breakthroughs"
    },
    "product": {
        "name": "Products",
        "icon": "💼",
        "description": "New products / Features / Corporate news"
    },
    "research": {
        "name": "Research",
        "icon": "📚",
        "description": "Academic research / Technical breakthroughs / Papers"
    },
    "tools": {
        "name": "Tools",
        "icon": "🛠️",
        "description": "Dev tools / Open source projects / SDKs"
    },
    "funding": {
        "name": "Funding",
        "icon": "💰",
        "description": "Investment / M&A / IPO"
    },
    "events": {
        "name": "Events",
        "icon": "🏆",
        "description": "Awards / Controversies / Policy / Regulation"
    }
}

# Mapping categories to themes (currently all blue)
CATEGORY_THEME_MAP = {
    "model": "blue",
    "product": "blue",
    "funding": "blue",
    "tools": "blue",
    "research": "blue",
    "events": "blue",
}

DEFAULT_THEME = "blue"
FIXED_THEME = "blue"

# Metadata for the generated website
SITE_META = {
    "title": "AI Daily",
    "subtitle": "AI News Daily",
    "description": "Daily AI news, smart classification, fast tracking",
    "author": "",
    "keywords": ["AI", "Artificial Intelligence", "Machine Learning", "Deep Learning", "News", "Daily"]
}

HTML_TEMPLATE_CONFIG = {
    "lang": "zh-CN",
    "charset": "UTF-8",
    "viewport": "width=device-width, initial-scale=1.0"
}

# Firefly API (for image generation, optional)
FIREFLY_API_URL = os.getenv("FIREFLY_API_URL", "https://fireflycard-api.302ai.cn/api/saveImg")
FIREFLY_API_KEY = os.getenv("FIREFLY_API_KEY", "")                
FIREFLY_DEFAULT_CONFIG = {
    "font": "SourceHanSerifCN_Bold",
    "align": "left",
    "width": 400,
    "height": 533,
    "fontScale": 1.2,
    "ratio": "3:4",
    "padding": 30,
    "switchConfig": {
        "showIcon": False,
        "showTitle": False,
        "showContent": True,
        "showTranslation": False,
        "showAuthor": False,
        "showQRCode": False,
        "showSignature": False,
        "showQuotes": False,
        "showWatermark": False
    },
    "temp": "tempBlackSun",
    "fonts": {
        "title": 2.1329337874720125,
        "content": 1.9079435748084854,
        "translate": 1.1415042034904328,
        "author": 0.801229782035275
    },
    "textColor": "rgba(0,0,0,0.8)",
    "subTempId": "tempBlackSun",
    "borderRadius": 15,
    "color": "pure-ray-1",
    "useFont": "SourceHanSerifCN_Bold",
    "useLoadingFont": True
}

ENABLE_IMAGE_GENERATION = os.getenv("ENABLE_IMAGE_GENERATION", "false").lower() == "true"

def get_theme(theme_name: str) -> dict:
    """Get configuration for a specific theme"""
    return THEMES.get(theme_name, THEMES[DEFAULT_THEME])

def get_category_info(category_key: str) -> dict:
    """Get information for a specific news category"""
    return CATEGORIES.get(category_key, CATEGORIES["model"])

def guess_theme_from_content(content_analysis: dict) -> str:
    """Determine the best theme based on the content analysis (e.g., dominant category)"""
    if not content_analysis or "categories" not in content_analysis:
        return DEFAULT_THEME
    categories = content_analysis.get("categories", [])
    if not categories:
        return DEFAULT_THEME
    # Find the category with the most news items
    max_category = max(categories, key=lambda x: len(x.get("items", [])))
    category_key = max_category.get("key", "")
    return CATEGORY_THEME_MAP.get(category_key, DEFAULT_THEME)
